name: Generate Embeddings
on:
  push:
    branches:
      - master
    paths:
      - 'website/src/pages/docs/**'
      - 'website/src/pages/plugins/**'

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: yarn

      - name: run embeddings script
        working-directory: website
        run: yarn embeddings
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
